"""empty message

Revision ID: 504775af6ac0
Revises: 9be62b6fae35
Create Date: 2021-03-24 18:30:50.521207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504775af6ac0'
down_revision = '9be62b6fae35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('criticId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'criticId')
    # ### end Alembic commands ###
